# Generated by Django 4.2.19 on 2025-02-06 17:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='city_other',
            field=models.CharField(blank=True, help_text='Em caso de outra cidade favor informa-la', max_length=80, verbose_name='Outra_cidade'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='course',
            field=models.CharField(blank=True, help_text='CURSO (CASO ESTEJA NA ESCOLA TÉCNICA OU NA FACULDADE):', max_length=80, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='deficincy_type',
            field=models.CharField(blank=True, help_text='VOCÊ POSSUI ALGUM TIPO DE DEFICIÊNCIA? SE SIM, PODERIA NOS DIZER QUAL?', max_length=80, verbose_name='deficiencia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='ethnicity_other',
            field=models.CharField(blank=True, help_text='Em caso de outra etinia favor informa-la', max_length=80, verbose_name='etinia'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='intern_time',
            field=models.CharField(blank=True, help_text='CEM QUAIS HORÁRIOS VOCÊ TRABALHA OU FAZ ESTÁGIO? ', max_length=80, verbose_name='horarios'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='knowloge_other',
            field=models.CharField(blank=True, help_text='COMO VOCÊ FICOU SABENDO DAS INSCRIÇÕES PARA O PROCESSO SELETIVO DESTE ANO? ', max_length=80, verbose_name='conhecimento'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='parent',
            field=models.CharField(blank=True, help_text='Nome completo do responsável ', max_length=80, verbose_name='Responsalvel'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='parent_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='special_interview',
            field=models.CharField(blank=True, help_text='SE SIM, PODERIA NOS DIZER QUAL?', max_length=80, verbose_name='cuidado_entrevista'),
        ),
    ]
