# Generated by Django 4.2.19 on 2025-02-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0004_inscription_gender_other_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='cpf',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='CPF'),
        ),
    ]
