# Generated by Django 4.2.19 on 2025-02-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0005_alter_inscription_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file_uploads/'),
        ),
    ]
