# Generated by Django 4.2.19 on 2025-02-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0006_inscription_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='slug',
        ),
    ]
