# Generated by Django 4.2.19 on 2025-02-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaings', '0007_remove_inscription_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='tablet',
            field=models.CharField(default='OK', help_text='Clique para selecionar', max_length=100, verbose_name='tablet'),
        ),
    ]
